meta:
  title: Open Source @ Ripple
  description: Open source projects and prerelease documentation being developed by Ripple engineers.
  siteUrl: https://opensource.ripple.com
  keywords: xrpl docs, prerelease docs, beta api reference docs
  lang: en-US
disableImagesOptimization: true
linkChecker:
  severity: warning
  options:
    CheckExternal: false
logo:
  image: ./images/ripple-open-source-logo.svg
  altText: Open Source at Ripple Documentation
toc:
  enable: true
editPage:
  baseUrl: https://github.com/ripple/opensource.ripple.com/tree/main/
  icon: ./images/pen-to-square-solid.svg
copyCodeSnippet:
  enable: true
  buttonText: Copy
  tooltipText: Copy the code snippet
  toasterText: Copied!
  toasterDuration: 1500   
stylesheets:
  - ./static/style.css
  - ./static/fonts.css
# https://redocly.com/docs/developer-portal/configuration/siteconfig/analytics/#google-global-site-tag-gtagjs
analytics:
  gtag:
    # note that GA doesn't work in the development environment
    trackingIds:
        - "G-S1KBMRJYKS" #Google Analytics / GA
    pluginConfig:
      head: true
#scripts:
#  - ./static/intercom.js
nav:
  - label: Home
    page: index.mdx  
  - label: Open Source Projects
    page: docs/index.md    
  - search: true

showNextButton: false

footer:
  columns:
    - group: About
      items:
        - label: Ripple
          href: https://ripple.com
          external: true 
        - label: XRPL Overview
          href: https://xrpl.org/xrp-ledger-overview.html
          external: true                            
    - group: Resources
      items:
        - label: XRP Ledger Docs
          href: https://xrpl.org/docs.html
          external: true
        - label: Contribute to the XRP Ledger 
          href: https://xrpl.org/contribute-code.html
          external: true  
    - label: © 2013 - 2023 Ripple, All Rights Reserved.
disableLastModified: true
